import { Controller, Get, Param } from '@nestjs/common';
import { GestFormService } from '../../services/gest-form/gest-form.service';

@Controller('gest-form')
export class GestFormController {
  constructor(private readonly gestFormService: GestFormService) {}

  /*
  ** passthrough GET handler that return the values of the call to gestFormService
  **
  ** @Input: quantity wanted to be fed to the gestFormService (Optional)
  ** @Output: Array of values generated by the gestFormService
  */
  @Get(':qty?')
  generateGestFormValues(@Param() params): (string | number)[] {
    return this.gestFormService.generate(params.qty);
  }
}
